#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1639952700                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : /presskit.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : # SugarBot - Sugar and Food tracker                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : # Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Be aware of sugar intake and how it affects your health with SugarBot.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Majid Jabrayilov
your_link                                 : https://swiftwithmajid.com
your_city                                 : Baku                                
email_address                             : cmecid@gmail.com
facebook_username                         : majid.jabrayilov                                     
instagram_username                        : mecid8
twitter_username                          : mecid
github_username                           : mecid
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Food logging
    description                           : Logging food is a proven method for losing weight, eating healthier, and reaching peak athletic goals.
    fontawesome_icon_name                 : balance-scale
    
  - title                                 : Sugar tracking
    description                           : Regular sugar monitoring is the most important thing you can do to manage type 1 or type 2 diabetes.
    fontawesome_icon_name                 : star-of-life

  - title                                 : Insights
    description                           : You’ll be able to see what makes your numbers go up or down, such as eating different foods, taking your medicine, or being physically active.
    fontawesome_icon_name                 : chart-bar
  
  - title                                 : Recommendations
    description                           : An intelligent recommendations system gives you hints on maintaining macro and micro nutrients intake.
    fontawesome_icon_name                 : comment

  - title                                 : GPT assistant
    description                           : Describe your dish, and SugarBot GPT calculates calories and sugar instantly.
    fontawesome_icon_name                 : wang-magic

  - title                                 : Personal goal plan
    description                           : SugarBot prepares personalized goals plan by analyzing data from Apple Health.
    fontawesome_icon_name                 : calculator 



# Theme Settings
topbar_color                              : "#000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#000"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000"
cover_overlay_transparency                : 0.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000"

link_color                                : "#32e33b"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#32e33b"
feature_icons_background_color            : "#222"

social_icons_foreground_color             : "#32e33b"
social_icons_background_color             : "#222"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
